language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
#  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script:
  - phpunit -c app/

#notifications:
#  email:
#    -  sergey.stribaylo@gmail.com
